name: Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '*.tf'
      - 'modules/**'
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: catalystsquad/action-semantic-release-general@v1
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
